name: Asperger Media | Autistic. Information Tech.
markdown: kramdown
permalink: /blog/:title
collections:
  staff_members:
    output: true
  drafts:
    output: true
defaults:
    scope:
      path: ""
      type: drafts
    values:
      layout: draft