name: Asperger Media | Autistic. Information Tech.
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
collections:
  staff_members:
    output: true
  drafts:
    output: true
defaults:
    scope:
      path: "/blog/drafts"
      type: drafts
    values:
      layout: draft